spring:
  application:
    name: user-microservice # The name of the application for identification in Eureka
  cloud:
    config:
      uri: http://localhost:8888 # The URI of your Config Server, where configuration properties are stored
      import: "optional:configserver:" # Correct use of 'configserver' with 'optional' to prevent errors if config server is not available
      import-check:
        enabled: false # Disable the check for configuration import from the Config Server
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/ # The URI of your Eureka Server for service discovery

management:
  tracing:
    sampling:
      probability: 1.0 # Sampling rate for tracing (1.0 means all requests will be traced)
  zipkin:
    endpoint: http://localhost:9411/api/v2/spans # The URL of the Zipkin server to collect and visualize traces

